### ISSUE TITLE
Profile and update

### ISSUE THREAD

**Issue by icekang** [2110423-2019-2/sec3_OldFavor#4]
Profile and update page for users and design!

**Comment by pewtpong** [comment]
ดีมาก

รับ Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by icekang** [comment]
เยี่ยมจริง ๆ

Best Regards,
Naravich Chutisilp

On 19 Feb BE 2563, at 01:05, pewt1403 <notifications@github.com> wrote:

﻿ดีมาก

รับ Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by pewtpong** [comment]
ใครไม่มาย แต่พี่มาย
Best regards, ทัศนัย ภูวดล

รับ Outlook for Android<https://aka.ms/ghei36>
________________________________
